spring:
  application:
    name: webrtc

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  # 터미널 색 추가
  output:
    ansi:
      enabled: always

  threads:
    virtual:
      enabled: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

app:
  go2rtc:
    binary: ./go2rtc
    config: ./go2rtc.yml
    api-url: http://localhost:1984
  camera:
    ip: ${CAM_IP:192.168.0.80}
    isapi-port: ${ISAPI_PORT:80}
    isapi-user: ${CAM_RTSP_USER:admin}
    isapi-pass: ${CAM_RTSP_PASS:admin}
